version: 2
jobs:
  build-and-test:
    working_directory: ~/repo
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ~/repo/node_modules
      - run:
          name: test
          command: yarn test
      - run:
          name: build
          command: yarn build
  npm-upgrade:
    working_directory: ~/repo
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install
          command: yarn install
      - run:
          name: upgrade
          command: yarn run upgrade
      - run:
          name: test
          command: yarn test
      - run:
          name: build
          command: yarn build
      - run:
          name: github push
          command: './scripts/git_push.sh'

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build-and-test
  upgrade:
    jobs:
      - npm-upgrade
    triggers:
      - schedule:
          cron: "00 1 * * 1" # 毎週月曜日
          filters:
            branches:
              only:
                - master
